version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    container_name: redis-container

  go-subscribe:
    build: .
    tty: true
    volumes:
      - ./src:/go/src/work
    entrypoint: "go run /go/src/work/subscribe.go"

  go-publish:
    build: .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./src:/go/src/work
    entrypoint: "go run /go/src/work/publish.go"
